# Site settings
main:
  title: UX design engineering
  sub-title: Front end meets UX
  email: me@chrisgibbons.co.uk
  description: Chris Gibbons // Front End Web Developer from Lancashire, UK.
  author: Chris Gibbons

baseurl:  # the subpath of your site, e.g. /blog/
url: "http://www.chrisgibbons.co.uk" # the base hostname & protocol for your site

meta:
  description: "Chris is a senior front end, UX developer based in Blackpool, Lancashire &amp; Manchester, UK. He build's flexible responsive websites for the all users of the web and bakes a smashing cake."
  title: "Chris Gibbons // Friendly front end web developer based in Manchester in the North West of England"
  keywords: "Chris Gibbons, chris, gibbons, gbbns, blackpool, lancashire,england, uk, united kingdom, html, css, xhtml, web standards, accessibility, javascript"

# Internal nav
nav:
  main:
    writing: "/writing"
    projects: "/projects"
    now: "/now"

social-link:
  twitter: jibubo
  github:  gbbns
  linkedin: cdgibbons
  lastfm: jibubo
  flickr: jibubo
  instagram: jibubo
  vsco: jibubo
  500px: jibubo

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title

exclude:
  - node_modules/
  - package.json
  - gulpfile.js
  - css/

keep_files:
  - css/main.css
