# Site settings
title: Chris Gibbons.
email: me@chrisgibbons.co.uk
description: Chris Gibbons // point12 - Front End Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrisgibbons.co.uk" # the base hostname & protocol for your site

sass:
  sass_dir: _sass
  style: expanded

social-link:
  twitter: jibubo
  github:  point12
  linkedin: cdgibbons
  lastfm: jibubo
  flickr: jibubo
  instagram: jibubo

# Build settings
markdown: kramdown

permalink: /:year/:month/:title
