# Site settings
main:
  title: Chris Gibbons.
  email: me@chrisgibbons.co.uk
  description: Chris Gibbons // point12 - Front End Web Developer

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrisgibbons.co.uk" # the base hostname & protocol for your site

meta:
  description: "Chris Gibbons, a senior front end &amp; freelance developer based in Blackpool, Lancashire &amp; Manchester, UK. I build flexible responsive websites for the web. Please get in touch for more information!"
  title: "Freelance front end web developer -- Manchester - Lancashire -- Chris Gibbons"
  keywords: "Chris Gibbons, chris gibbons, point12, blackpool, lancashire,england, uk, united kingdom, html, css, xhtml, web standards, accessibility, javascript"

sass:
  sass_dir: _sass
  style: expanded

social-link:
  twitter: jibubo
  github:  point12
  linkedin: cdgibbons
  lastfm: jibubo
  flickr: jibubo
  instagram: jibubo

# Build settings
markdown: kramdown

permalink: /:year/:month/:title
