# Site settings
main:
  title: UX design engineering
  email: me@chrisgibbons.co.uk
  description: Chris Gibbons // Front End Web Developer from Lancashire, UK.
  author: Chris Gibbons

baseurl: / # the subpath of your site, e.g. /blog/
url: "http://www.chrisgibbons.co.uk" # the base hostname & protocol for your site

meta:
  description: "Chris Gibbons a senior front end, UX developer based in Blackpool, Lancashire &amp; Manchester, UK. I build flexible responsive websites for the all users of the web!"
  title: "Freelance front end web developer -- Manchester - Lancashire -- Chris Gibbons"
  keywords: "Chris Gibbons, chris gibbons, gbbns, blackpool, lancashire,england, uk, united kingdom, html, css, xhtml, web standards, accessibility, javascript"

sass:
  sass_dir: _sass
  style: compact

social-link:
  twitter: jibubo
  github:  gbbns
  linkedin: cdgibbons
  lastfm: jibubo
  flickr: jibubo
  instagram: jibubo

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title
